# Generated by Django 5.0.3 on 2024-04-03 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastSchoolAttended', models.CharField(max_length=100)),
                ('schoolAddress', models.TextField()),
                ('yearGraduated', models.IntegerField(null=True)),
                ('degree', models.CharField(max_length=100)),
                ('achievements', models.TextField()),
                ('prcNumber', models.CharField(max_length=20)),
                ('expirationDate', models.DateField(null=True)),
                ('yearsOfTeaching', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mothersName', models.CharField(max_length=100)),
                ('mothersContact', models.CharField(max_length=20)),
                ('mothersOccupation', models.CharField(max_length=100)),
                ('mothersAddress', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adviser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeID', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('gradeLevel', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('academicData', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userform.academicdata')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gradeLevel', models.IntegerField(null=True)),
                ('section', models.CharField(max_length=20, null=True)),
                ('adviser', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10, null=True)),
                ('parents', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userform.parent')),
            ],
        ),
        migrations.CreateModel(
            name='Userform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=20)),
                ('adviser', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userform.adviser')),
                ('student', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='userform.student')),
            ],
        ),
    ]
