# Generated by Django 4.2.7 on 2024-05-06 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('lastSchoolAttended', models.CharField(max_length=100)),
                ('schoolAddress', models.TextField()),
                ('yearGraduated', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('prcNumber', models.CharField(max_length=100)),
                ('expirationDate', models.DateField(null=True)),
                ('yearsOfTeaching', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('mothersName', models.CharField(max_length=100)),
                ('mothersContact', models.CharField(max_length=100)),
                ('mothersOccupation', models.CharField(max_length=100)),
                ('m_dob', models.DateField(null=True)),
                ('m_age', models.IntegerField(null=True)),
                ('fathersName', models.CharField(max_length=100)),
                ('fathersContact', models.CharField(max_length=100)),
                ('fathersOccupation', models.CharField(max_length=100)),
                ('f_dob', models.DateField(null=True)),
                ('f_age', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('studentID', models.CharField(max_length=100, unique=True)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('gradeLevel', models.CharField(max_length=100, null=True)),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='userform.parent')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='userform.section')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('employeeID', models.CharField(max_length=100, unique=True)),
                ('lastName', models.CharField(max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('middleName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('dob', models.DateField(null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('academic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='userform.academic')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=20)),
                ('student', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userform.student')),
                ('teacher', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userform.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SectionHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField()),
                ('grade_level', models.CharField(max_length=50)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_handles', to='userform.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_handles', to='userform.teacher')),
            ],
        ),
    ]
