# Generated by Django 4.2.7 on 2024-05-07 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0002_enrollment_remove_student_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='userform.sectionhandle'),
        ),
    ]
