# Generated by Django 4.2.7 on 2024-05-14 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0008_remove_attendance_created_at_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
