# Generated by Django 4.2.7 on 2024-05-14 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0009_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
