# Generated by Django 4.2.7 on 2024-05-18 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0012_section_alter_sectionhandle_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionhandle',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_handle', to='userform.teacher'),
        ),
    ]
