# Generated by Django 4.2.7 on 2024-05-18 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0013_alter_sectionhandle_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='section_handle',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_rel', to='userform.sectionhandle'),
        ),
        migrations.AlterField(
            model_name='sectionhandle',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='section_handle_rel', to='userform.teacher'),
        ),
    ]
