# Generated by Django 4.2.7 on 2024-05-18 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0014_teacher_section_handle_alter_sectionhandle_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecthandle',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_handles', to='userform.section'),
        ),
    ]
