# Generated by Django 4.2.7 on 2024-05-18 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0015_alter_subjecthandle_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjecthandle',
            name='section',
            field=models.CharField(max_length=50),
        ),
    ]
