# Generated by Django 4.2.7 on 2024-05-18 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0019_alter_subjecthandle_section'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subjecthandle',
            unique_together={('teacher', 'subject')},
        ),
    ]
