# Generated by Django 4.2.7 on 2024-05-20 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0020_alter_subjecthandle_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'present'), ('Absent', 'absent')], max_length=10),
        ),
    ]
