# Generated by Django 4.2.7 on 2024-05-22 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0023_alter_sectionhandle_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='userform.enrollment'),
        ),
    ]
