# Generated by Django 4.2.7 on 2024-05-22 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0026_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='enrollment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userform.enrollment'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'enrollment', 'date')},
        ),
    ]
