# Generated by Django 4.2.7 on 2024-05-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0028_alter_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
