# Generated by Django 4.2.7 on 2024-05-27 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0030_alter_attendance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grading_period', models.CharField(choices=[('1st Grading', '1st Grading'), ('2nd Grading', '2nd Grading'), ('3rd Grading', '3rd Grading'), ('4th Grading', '4th Grading')], max_length=20)),
                ('grade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='userform.student')),
                ('subject_handle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='userform.subjecthandle')),
            ],
        ),
    ]
