# Generated by Django 4.2.7 on 2024-05-31 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userform', '0031_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='grade_level',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='grade_level',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
